name: 'Setup My Env'
description: 'Sets up git and installs python requirements'
runs:
  using: "composite"
  steps:
    - name: git config
      run: |
        git config --global user.name 'certcc-ghbot'
        git config --global user.email 'cert+ghbot@cert.org'
      shell: bash

    - name: install packages
      run: |
        python --version
        pip install -r requirements.txt
        python setup.py install
      shell: bash
          
