name: Deep Dive 2021

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  deep dive:
    runs-on: ubuntu-latest
       
    strategy:
      max-parallel: 1
      matrix:
        month: ['08', '07', '06', '05', '04', '03', '02', '01']
      
    steps:
      - name: checkout
        uses: actions/checkout@v2
      
      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
          
      - name: setup env
        uses: ./.github/actions/setup_my_env
  
      # in case things have changed since we we spawned
      - name: git pull
        run: git pull
        
      - name: do_deep_dive
        run: crawl_files --verbose results/2021/${{ matrix.month }}/2021-${{ matrix.month }}_summary.json
          
      - name: add and commit
        uses: ./.github/actions/commit_results
        with:
          results_dir: data
          commit_msg: ${{ github.workflow }} deep dive 2021/${{ matrix.month }}
          
      - name: push result
        uses: ./.github/actions/pull_rebase_push_retry
