name: Update Summaries

# Controls when the workflow will run
on:
  # run when SearchRepos completes
  workflow_run:
    workflows: ["SearchRepos"]
    types:
      - completed

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  update_summaries:
    runs-on: ubuntu-latest

    steps:
      - name: Get dates
        id: date
        run: |
          echo "::set-output name=today::$(date +'%Y-%m-%d')"
          echo "::set-output name=yesterday::$(date -d yesterday '+%Y-%m-%d')"
          echo "::set-output name=this_month::$(date +'%Y-%m')"
          echo "::set-output name=this_year::$(date +'%Y')"

      - name: checkout
        uses: actions/checkout@v2

      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: setup env
        uses: ./.github/actions/setup_my_env

      - name: summarize yesterday
        uses: ./.github/actions/generate_summaries
        with:
          ymd_option: '--day'
          ymd_value: ${{ steps.date.outputs.yesterday }}

      - name: add and commit
        uses: ./.github/actions/commit_results
        with:
          commit_msg: ${{ github.workflow }} for day ${{ steps.date.outputs.yesterday }}

      - name: summarize today
        uses: ./.github/actions/generate_summaries
        with:
          ymd_option: '--day'
          ymd_value: ${{ steps.date.outputs.today }}

      - name: add and commit
        uses: ./.github/actions/commit_results
        with:
          commit_msg: ${{ github.workflow }} for day ${{ steps.date.outputs.today }}

      - name: summarize this month
        uses: ./.github/actions/generate_summaries
        with:
          ymd_option: '--month'
          ymd_value: ${{ steps.date.outputs.this_month }}

      - name: add and commit
        uses: ./.github/actions/commit_results
        with:
          commit_msg: ${{ github.workflow }} for month ${{ steps.date.outputs.this_month }}

      - name: push results
        uses: ./.github/actions/pull_rebase_push_retry
